# coding: utf-8

"""
Suppose you have some texts of news and know their categories.
You want to train a system with this pre-categorized/pre-classified
texts. So, you have better call this data your training set.
"""

# You need to train the system passing each text one by one to the trainer module.
newsSet = [
	#Général
    {'text': 'oui bonjour je vous écoute', 'category': 'hello'},
    {'text': 'salut la team', 'category': 'hello'},
    {'text': 'hello', 'category': 'hello'},
    {'text': 'hello', 'category': 'hello'},
    {'text': 'coucou', 'category': 'hello'},
    {'text': 'connasse', 'category': 'insulte'},
    {'text': 'pétasse', 'category': 'insulte'},
    {'text': 'pute', 'category': 'insulte'},
    {'text': 'conne', 'category': 'insulte'},
    {'text': 'incompétente', 'category': 'insulte'},
    {'text': 'stupide', 'category': 'insulte'},
	{'text': 'ta mère', 'category': 'insulte'},
    {'text': 'ciao', 'category': 'tiao'},
    {'text': 'bye', 'category': 'tiao'},
    {'text': 'au revoir', 'category': 'tiao'},
    {'text': 'merci, bonne journée !', 'category': 'tiao'},
    {'text': 'top merci pour votre aide', 'category': 'tiao'},
    {'text': 'bisous', 'category': 'tiao'},
    {'text': 'je veux manger', 'category': 'manger'},
	{'text': 'j’ai la dalle', 'category': 'manger'},
	{'text': 'j’ai faim', 'category': 'manger'},
	{'text': 'je veux manger', 'category': 'manger'},
	{'text': 'manger', 'category': 'manger'},
	{'text': 'je veux de la nourriture', 'category': 'manger'},
	{'text': 'j’aimerai manger', 'category': 'manger'},
	{'text': 'je veux déjeuner', 'category': 'manger'},
	{'text': 'je veux dîner', 'category': 'manger'},
	{'text': 'j’ai un petit creux', 'category': 'manger'}, 
	{'text': 'où manger', 'category': 'manger'},
	{'text': 'où bouffer', 'category': 'manger'},
	{'text': 'où déjeuner', 'category': 'manger'},
	{'text': 'où diner', 'category': 'manger'},
	{'text': 'restaurant à proximité', 'category': 'manger'},
	{'text': 'restaurant pas loin', 'category': 'manger'},
	{'text': 'resto', 'category': 'manger'},
	{'text': 'restau', 'category': 'manger'},
	{'text': 'restaurant', 'category': 'manger'},
	{'text': 'fast Food', 'category': 'manger'},
	{'text': 'restauration rapide', 'category': 'manger'},
	{'text': 'manger vite', 'category': 'manger'},
	{'text': 'je veux manger au restaurant', 'category': 'manger'},
	{'text': 'je veux dîner au restaurant', 'category': 'manger'},
	{'text': 'feed me senpai', 'category': 'manger'},
	{'text': 'please feed the troll', 'category': 'manger'},
	{'text': 'hungry', 'category': 'manger'},
	{'text': 'j’arrive pas à ne pas avoir faim', 'category': 'manger'},

    #Les restaurants
    {'text': 'chipotle', 'category': 'Mexicano'},
    {'text': 'mc Donalds', 'category': 'Burger'},
    {'text': 'five Guys', 'category': 'Burger'},
    {'text': 'in&Out', 'category': 'Burger'},
    {'text': 'wendys', 'category': 'Burger'},
    {'text': 'macdo', 'category': 'Burger'},
    {'text': 'KFC', 'category': 'Poulet'},
    {'text': 'quick', 'category': 'Burger'},
    {'text': 'grec', 'category': 'Kebab'},
    {'text': 'tacos', 'category': 'Tacos'},
    {'text': 'pizza', 'category': 'Pizza'},
    {'text': 'pizza Hut', 'category': 'Pizza'},
    {'text': 'dominos Pizza', 'category': 'Pizza'},
    {'text': 'chinois', 'category': 'Chinois'},
    {'text': 'tang Frère', 'category': 'Chinois'},
    {'text': 'sushi', 'category': 'Japonais'},
    {'text': 'jap', 'category': 'Japonais'},
    {'text': 'japonais', 'category': 'Japonais'},
    {'text': 'nouilles', 'category': 'Japonais'},
    {'text': 'sushi Shop', 'category': 'Japonais'},
    {'text': 'sushi West', 'category': 'Japonais'},
    {'text': 'planet Sushi', 'category': 'Japonais'},
    {'text': 'burger King', 'category': 'Burger'},
    {'text': 'east Side Burgers', 'category': 'Burger'},
    {'text': 'paul', 'category': 'Sandwich'},
    {'text': 'burger', 'category': 'Burger'},
    {'text': 'brioche Dorée', 'category': 'Sandwich'},
    {'text': 'la Mie Caline', 'category': 'Sandwich'},
    {'text': 'subway', 'category': 'Sandwich'},
    {'text': 'boulangerie', 'category': 'Sandwich'},
    {'text': 'sushi', 'category': 'Japonais'},
    {'text': 'pasta Cosy', 'category': 'Pâtes'},

    #Les boissons
    {'text': 'sprite', 'category': 'gazeux'},
	{'text': 'coca', 'category': 'gazeux'},
    {'text': 'orangina', 'category': 'gazeux'},
    {'text': 'badoit', 'category': 'gazeux'},
    {'text': 'schweps', 'category': 'gazeux'},
    {'text': 'fanta', 'category': 'gazeux'},
    {'text': 'limonade' , 'category': 'gazeux'},
    {'text': 'pepsi', 'category': 'gazeux'},
    {'text': 'canada dry', 'category': 'gazeux'},
    {'text': 'oasis', 'category': 'plat'},
    {'text': 'red bull', 'category': 'plat'},
    {'text': 'ice tea', 'category': 'plat'},
    {'text': 'minute maid', 'category': 'plat'},

    #Indésirable
    {'text': 'Salade', 'category': 'indesirable'},
	{'text': 'Oignon', 'category': 'indesirable'},
	{'text': 'Mais', 'category': 'indesirable'},
	{'text': 'Endive', 'category': 'indesirable'},
	{'text': 'Epinard', 'category': 'indesirable'},
	{'text': 'Aubergine', 'category': 'indesirable'},
	{'text': 'Navet', 'category': 'indesirable'},
	{'text': 'Cornichon', 'category': 'indesirable'},
	{'text': 'Préparation non casher', 'category': 'indesirable'},
	{'text': 'Préparation non halal', 'category': 'indesirable'},
	{'text': 'Oeuf', 'category': 'indesirable'},
	{'text': 'Viande', 'category': 'indesirable'},
	{'text': 'Poisson', 'category': 'indesirable'},
	{'text': 'Epices', 'category': 'indesirable'},
	{'text': 'Herbes aromatiques', 'category': 'indesirable'},
	{'text': 'Matières grasses', 'category': 'indesirable'},
	{'text': 'Sel', 'category': 'indesirable'},
	{'text': 'Poivre', 'category': 'indesirable'},
	{'text': 'Sucre', 'category': 'indesirable'},
	{'text': 'Beurre', 'category': 'indesirable'},
	{'text': 'Crème', 'category': 'indesirable'},
	{'text': 'Gélatine', 'category': 'indesirable'},
	{'text': 'Gluten', 'category': 'indesirable'},
	{'text': 'Fromage', 'category': 'indesirable'},


    #Arrondissement 
    {'text': 'premier', 'category': 'arrondissement'},
	{'text': '1er', 'category': 'arrondissement'},
    {'text': 'deuxieme', 'category': 'arrondissement'},
    {'text': '2e', 'category': 'arrondissement'},
    {'text': 'troiseme', 'category': 'arrondissement'},
    {'text': '3e', 'category': 'arrondissement'},
    {'text': 'quatrieme' , 'category': 'arrondissement'},
    {'text': '4e', 'category': 'arrondissement'},
    {'text': 'cinquieme', 'category': 'arrondissement'},
    {'text': '5e', 'category': 'arrondissement'},
    {'text': 'sixieme', 'category': 'arrondissement'},
    {'text': '6e', 'category': 'arrondissement'},
    {'text': 'septieme', 'category': 'arrondissement'},
    {'text': '7e', 'category': 'arrondissement'},
    {'text': 'huitieme', 'category': 'arrondissement'},
    {'text': '8e', 'category': 'arrondissement'},
    {'text': 'neuvieme', 'category': 'arrondissement'},
    {'text': '9e', 'category': 'arrondissement'},
    {'text': 'dixieme', 'category': 'arrondissement'},
    {'text': '10e', 'category': 'arrondissement'},
    {'text': 'onzieme', 'category': 'arrondissement'},
    {'text': '11e', 'category': 'arrondissement'},
    {'text': 'douzieme', 'category': 'arrondissement'},
    {'text': '12e', 'category': 'arrondissement'},
    {'text': 'treizieme', 'category': 'arrondissement'},
    {'text': '13e', 'category': 'arrondissement'},
    {'text': 'quatorzieme', 'category': 'arrondissement'},
    {'text': '14e', 'category': 'arrondissement'},
    {'text': 'quinzieme', 'category': 'arrondissement'},
    {'text': '15e', 'category': 'arrondissement'},
    {'text': 'seizieme', 'category': 'arrondissement'},
    {'text': '16e', 'category': 'arrondissement'},
    {'text': 'dixseptieme', 'category': 'arrondissement'},
    {'text': '17e', 'category': 'arrondissement'},
    {'text': 'dixhuitieme', 'category': 'arrondissement'},
    {'text': '18e', 'category': 'arrondissement'},
    {'text': 'dixneuvieme', 'category': 'arrondissement'},
    {'text': '19e', 'category': 'arrondissement'},
    {'text': 'vingtieme', 'category': 'arrondissement'},
    {'text': '20e', 'category': 'arrondissement'},


]